---
linters:
  enable-all: true
  disable:
    # Deprecated
    - deadcode
    - ifshort
    - scopelint
    - maligned
    - golint
    - varcheck
    - nosnakecase
    - structcheck
    - interfacer
    - exhaustivestruct
    # Conflicts with gofmt
    - wsl
    # I do like some empty structs
    - exhaustruct
    # Although useful, sometimes I need to return with errors before ending the functions
    - wrapcheck
    # Since I'm not making a package in itself, no need for a specific test sub-package
    - testpackage

linters-settings:
  # Packages allowed
  depguard:
    rules:
      prevent_unmaintained_packages:
        # allow unless explicitly denied
        files:
          - $all
          - $test
        allow:
          - $gostd
          - github.com/joho/godotenv
          - git.xdol.org/xdol/xtrace/internal/trace
          - git.xdol.org/xdol/xtrace/internal/router
          - git.xdol.org/xdol/xtrace/internal/config
          - git.xdol.org/xdol/xtrace/internal/constant
  # Default values conflicts with gofmt
  lll:
    line-length: 160
    tab-width: 1